name: Post Issue to Slack

on:
  issues:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Post to Slack
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          # channel: #doctopus-tests - https://solo-io-corp.slack.com/archives/C04DYBSJK0R
          # SLACK_CHANNEL_ID: C04DYBSJK0R
          # doctopus-tests-kkb test channel https://solo-io-corp.slack.com/archives/C0A93CCSFQC
          SLACK_CHANNEL_ID: C0A93CCSFQC
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL_ID }}",
              "text": "New issue created: ${{ github.event.issue.title }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "New Issue Created"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n ${{ github.repository }} \n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Issue #:*\n #${{ github.event.issue.number }} \n"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Title:*\n${{ github.event.issue.title }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author:*\n${{ github.event.issue.user.login }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Description:*\n${{ github.event.issue.body }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Issue"
                      },
                      "url": "${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }